### PR TITLE
Updated the code to work with TensorFlow 1.0.1

### PR DESCRIPTION
**Pull request by dvaldivia**
This PR makes the basic changes to update the code to use `TensorFlow` 1.0.1

Please note that I also updated `eval.py` to reflect the documented default values and not the previously hardcoded ones.

### CODE REVIEW

**Comment by dvaldivia** [comment]
This is also requested on Issue #9

**Comment by hardikmeisheri** [comment]
@dvaldivia your code gives error match_valid.tsv not found

**Comment by dvaldivia** [comment]
@hardikmeisheri could you be more specific? this PR explicitly remove the hardcoded `match_valid.tsv`

**Comment by hardikmeisheri** [comment]
@dvaldivia Solved it. Sorry, error was on my side.

**Comment by vijaydwivedi75** [comment]
After changing `tf.nn.bidirectional_rnn` to `tf.contrib.rnn.static_bidirectional_rnn`, i am getting the following error.

`Traceback (most recent call last):
  File "train.py", line 64, in <module>
    batch_size=FLAGS.batch_size)
  File "/home/vijay321/Desktop/IASNLP/codes/siamese_dhwaj/siamese_network.py", line 77, in __init__
    self.out1=self.BiRNN(self.embedded_chars1, self.dropout_keep_prob, "side1", embedding_size, sequence_length)
  File "/home/vijay321/Desktop/IASNLP/codes/siamese_dhwaj/siamese_network.py", line 41, in BiRNN
    outputs, _, _ = tf.contrib.rnn.static_bidirectional_rnn(lstm_fw_cell_m, lstm_bw_cell_m, x, dtype=tf.float32)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 337, in static_bidirectional_rnn
    sequence_length, scope=fw_scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 197, in static_rnn
    (output, state) = call_cell()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 184, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 953, in __call__
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 713, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 235, in __call__
    with _checked_scope(self, scope or "basic_lstm_cell", reuse=self._reuse):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 77, in _checked_scope
    type(cell).__name__))`

`ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x7f0ccd77b4a8> with a different variable scope than its first use.  First use of cell was with scope 'bwside1/bidirectional_rnn/fw/multi_rnn_cell/cell_0/basic_lstm_cell', this attempt is with scope 'bwside1/bidirectional_rnn/fw/multi_rnn_cell/cell_1/basic_lstm_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([BasicLSTMCell(...)] * num_layers), change to: MultiRNNCell([BasicLSTMCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one for reverse).  In May 2017, we will start transitioning this cell's behavior to use existing stored weights, if any, when it is called with scope=None (which can lead to silent model degradation, so this error will remain until then.)`

Can anyone help regarding this?

**Comment by dvaldivia** [comment]
Was this on TensorFlow 1.0 or 1.1? I've seen this on 1.1 but not on 1.0

**Comment by vijaydwivedi75** [comment]
It's on TensorFlow 1.1.

**Comment by dvaldivia** [comment]
Yeah, I was not successful adapting this code to TF 1.1, I tried not making the RNNCell being reused, but there's a block where the context tries to access the same weights

**Comment by vijaydwivedi75** [comment]
So, any other way to resolve?

**Comment by kostaskk** [comment]
Hi Folks, In case you're still having issues getting this to work with later versions of Tensorflow. This is how I solved it. Replace the problematic area in siamese_network.py with the below:

`with tf.name_scope("fw"+scope),tf.variable_scope("fw"+scope):
            stacked_rnn_fw = []
            for _ in range(n_layers):
                fw_cell = tf.nn.rnn_cell.BasicLSTMCell(n_hidden, forget_bias=1.0, state_is_tuple=True)
                lstm_fw_cell = tf.contrib.rnn.DropoutWrapper(fw_cell,output_keep_prob=dropout)
                stacked_rnn_fw.append(lstm_fw_cell)
            lstm_fw_cell_m = tf.nn.rnn_cell.MultiRNNCell(cells=stacked_rnn_fw, state_is_tuple=True)

        with tf.name_scope("bw"+scope),tf.variable_scope("bw"+scope):
            stacked_rnn_bw = []
            for _ in range(3):
                bw_cell = tf.nn.rnn_cell.BasicLSTMCell(n_hidden, forget_bias=1.0, state_is_tuple=True)
                lstm_bw_cell = tf.contrib.rnn.DropoutWrapper(bw_cell,output_keep_prob=dropout)
                stacked_rnn_bw.append(lstm_bw_cell)
            lstm_bw_cell_m = tf.nn.rnn_cell.MultiRNNCell(cells=stacked_rnn_bw, state_is_tuple=True)

        with tf.name_scope("bw"+scope),tf.variable_scope("bw"+scope):
            outputs, _, _ = tf.nn.static_bidirectional_rnn(lstm_fw_cell_m, lstm_bw_cell_m, x, dtype=tf.float32)
`

**Pull request closed without merging**
